Repository Club-PARD/Hanmadi_WEB, pull requests merged in 2024-07, with the labels that each got.

#6 Feat: 카카오로그인 기능 추가
  namukkun-project/src/API/AxiosAPI.js
  namukkun-project/src/App.js
  namukkun-project/src/Assets/Style/theme.js
  namukkun-project/src/Components/Home_Components/Home.js
  namukkun-project/src/Components/Login_Components/KaKaoLogin.js
  namukkun-project/src/Components/Login_Components/LoginModal.js
  namukkun-project/src/Pages/HomePage.js
Labels: Feat

#7 Design: MainPage
  .DS_Store
  namukkun-project/src/App.js
  namukkun-project/src/Assets/Img/blueduck.svg
  namukkun-project/src/Assets/Img/img.txt
  namukkun-project/src/Assets/Img/imgcontent.svg
  namukkun-project/src/Assets/Img/logo.svg
  namukkun-project/src/Assets/Img/minilogo.svg
  namukkun-project/src/Assets/Img/pointer.svg
  namukkun-project/src/Assets/Img/whiteduck.svg
  namukkun-project/src/Assets/Style/theme.js
  namukkun-project/src/Components/Home_Components/Home.txt
  namukkun-project/src/Components/MainPage_Components/Banner.js
  namukkun-project/src/Components/MainPage_Components/Header.js
  namukkun-project/src/Components/MainPage_Components/IdeaPage.js
  namukkun-project/src/Pages/HomePage.js
  namukkun-project/src/Pages/MainPage.js
Labels: Design

#8 Desgn: mainpage완성
  namukkun-project/src/Assets/Img/bottombd.svg
  namukkun-project/src/Assets/Img/bottomwd.svg
  namukkun-project/src/Components/MainPage_Components/Banner.js
  namukkun-project/src/Components/MainPage_Components/GreatIdeaPage.js
  namukkun-project/src/Components/MainPage_Components/IdeaPage.js
  namukkun-project/src/Pages/MainPage.js
Labels: Design

#9 Feat: 메인페이지와 로그인 모달 연결
  namukkun-project/src/API/AxiosAPI.js
  namukkun-project/src/App.js
  namukkun-project/src/Assets/Img/ListBanner.svg
  namukkun-project/src/Components/Layout_Components/Header.js
  namukkun-project/src/Components/List_Components/ListregionSelect.js
  namukkun-project/src/Components/Login_Components/KaKaoLogin.js
  namukkun-project/src/Components/MainPage_Components/Header.js
  namukkun-project/src/Components/SelectRegion_Components/SelectRegions.js
  namukkun-project/src/Pages/ListPage.js
  namukkun-project/src/Pages/MainPage.js
  namukkun-project/src/Pages/SelectRegionPage.js
Labels: Design

#11 Design: 글자색 수정
  namukkun-project/src/Components/MainPage_Components/Banner.js
Labels: Design

#13 Design: 오리 위치 조정, inline수정
  namukkun-project/src/Components/Layout_Components/Header.js
  namukkun-project/src/Components/MainPage_Components/Banner.js
  namukkun-project/src/Components/MainPage_Components/GreatIdeaPage.js
  namukkun-project/src/Components/MainPage_Components/IdeaPage.js
Labels: Design

#15 Design: 모달 뒤로 화살표 이동
  namukkun-project/src/Pages/MainPage.js
Labels: Design

#17 Feat: 카카오 로그인 서버 연결 진짜 진짜 완료
  namukkun-project/src/API/AxiosAPI.js
  namukkun-project/src/Assets/Img/ListBanner.svg
  namukkun-project/src/Components/List_Components/ListregionSelect.js
  namukkun-project/src/Components/Login_Components/KaKaoLogin.js
  namukkun-project/src/Components/Login_Components/LoginModal.js
Labels: Feat, Design

#20 Design: 제안게시판 fixedbutton 추가
  namukkun-project/src/Assets/Img/hoversendbrave.svg
  namukkun-project/src/Components/List_Components/PopularPost.js
  namukkun-project/src/Pages/ListPage.js
Labels: Design

#21 Design: 제안게시판 페이지와 기존 코드 병합
  namukkun-project/src/API/AxiosAPI.js
  namukkun-project/src/Components/Login_Components/KaKaoLogin.js
  namukkun-project/src/Components/SelectRegion_Components/SelectRegions.js
Labels: Design

#22 Design: mypage 완성
  namukkun-project/src/App.js
  namukkun-project/src/Assets/Img/advisepen.svg
  namukkun-project/src/Assets/Img/face.svg
  namukkun-project/src/Assets/Img/mypageduck.svg
  namukkun-project/src/Assets/Img/uploadarrow.svg
  namukkun-project/src/Components/MainPage_Components/IdeaPage.js
  namukkun-project/src/Components/Mypage_Components/EndPost.js
  namukkun-project/src/Components/Mypage_Components/IngPost.js
  namukkun-project/src/Components/Mypage_Components/StatusBlock.js
  namukkun-project/src/Components/Mypage_Components/TempPost.js
  namukkun-project/src/Pages/ListPage.js
  namukkun-project/src/Pages/MyPage.js
Labels: Design

#24 Bug: conflict로 인한 push
  namukkun-project/src/App.js
  namukkun-project/src/Components/Postit_Components/DetailContent.js
  namukkun-project/src/Pages/Postit.js
Labels: Design, Bug

#27 Design: 라우터 경로 정리 & 모달 css 수정
  namukkun-project/src/App.js
  namukkun-project/src/Components/Layout_Components/Header.js
  namukkun-project/src/Components/Mypage_Components/RegionChangeModal.js
  namukkun-project/src/Components/WritingPage_Components/Writing.js
  namukkun-project/src/Components/WritingPage_Components/WritingModal.js
  namukkun-project/src/Components/WritingPage_Components/WritingPage.js
  namukkun-project/src/Pages/Postit.js
  namukkun-project/src/Pages/WritingPage.js
Labels: Fix, Design

#32 Feat, Design: postit 전반적인 기능 추가, postitpage css완성
  namukkun-project/package-lock.json
  namukkun-project/package.json
  namukkun-project/src/Assets/Img/advisepen 2.svg
  namukkun-project/src/Assets/Img/bluebackground.svg
  namukkun-project/src/Assets/Img/brownbackground.svg
  namukkun-project/src/Assets/Img/close.svg
  namukkun-project/src/Assets/Img/commentlike.svg
  namukkun-project/src/Assets/Img/exsuggest 2.svg
  namukkun-project/src/Assets/Img/face 2.svg
  namukkun-project/src/Assets/Img/fileimg 2.svg
  namukkun-project/src/Assets/Img/mypageduck 2.svg
  namukkun-project/src/Assets/Img/nexbutton.svg
  namukkun-project/src/Assets/Img/sendcomment.svg
  namukkun-project/src/Assets/Img/takenduck.svg
  namukkun-project/src/Assets/Img/uploadarrow 2.svg
  namukkun-project/src/Assets/Img/yellowbackground.svg
  namukkun-project/src/Components/Mypage_Components/EndPost 2.js
  namukkun-project/src/Components/Mypage_Components/IngPost 2.js
  namukkun-project/src/Components/Mypage_Components/StatusBlock 2.js
  namukkun-project/src/Components/Mypage_Components/TempPost 2.js
  namukkun-project/src/Components/Postit_Components/DetailContent.js
  namukkun-project/src/Pages/Postit.js
  namukkun-project/src/db/data.json
Labels: Feat, Design

#38 Feat: Postit 세부기능 추가
  namukkun-project/src/Assets/Img/aftertaken.svg
  namukkun-project/src/Assets/Img/bannerimg.svg
  namukkun-project/src/Assets/Img/bottomimg.svg
  namukkun-project/src/Assets/Img/defaultblue.svg
  namukkun-project/src/Assets/Img/defaultwhite.svg
  namukkun-project/src/Components/List_Components/ListSelectRegion.js
  namukkun-project/src/Components/List_Components/NewPost.js
  namukkun-project/src/Components/List_Components/PopularPost.js
  namukkun-project/src/Components/MainPage_Components/Banner.js
  namukkun-project/src/Components/MainPage_Components/GreatIdeaPage.js
  namukkun-project/src/Components/MainPage_Components/IdeaPage.js
  namukkun-project/src/Components/Postit_Components/DetailContent.js
  namukkun-project/src/Pages/Postit.js
  namukkun-project/src/db/data.json
Labels: Feat

#43 Design, Feat: 소개 페이지 텍스트 애니메이션 추가
  namukkun-project/src/Assets/Img/Bigdefault.svg
  namukkun-project/src/Assets/Img/EllipseLogin.svg
  namukkun-project/src/Assets/Img/logo.svg
  namukkun-project/src/Components/About_Components/AboutPage.js
  namukkun-project/src/Components/About_Components/TextAnimation.js
  namukkun-project/src/Components/Layout_Components/FixList.js
  namukkun-project/src/Components/Layout_Components/Header.js
  namukkun-project/src/Components/ListAll_Components/Contents.js
  namukkun-project/src/Components/ListAll_Components/ShowList.js
  namukkun-project/src/Components/List_Components/PopularPost.js
  namukkun-project/src/Components/Login_Components/LoginModal.js
  namukkun-project/src/Components/MainPage_Components/GreatIdeaPage.js
  namukkun-project/src/Recoil/Atom.js
Labels: Feat, Design

#57 Feat: list/listall/main 페이지 포스트 데이터 get 서버 연결
  namukkun-project/src/API/AxiosAPI.js
  namukkun-project/src/Assets/Img/hanmadiv.svg
  namukkun-project/src/Components/Layout_Components/FixList.js
  namukkun-project/src/Components/Layout_Components/Header.js
  namukkun-project/src/Components/ListAll_Components/Contents.js
  namukkun-project/src/Components/ListAll_Components/ShowList.js
  namukkun-project/src/Components/List_Components/ListSelectRegion.js
  namukkun-project/src/Components/List_Components/NewPost.js
  namukkun-project/src/Components/List_Components/PopularPost.js
  namukkun-project/src/Components/MainPage_Components/GreatIdeaPage.js
  namukkun-project/src/Components/MainPage_Components/IdeaPage.js
  namukkun-project/src/Components/Mypage_Components/RegionChangeModal.js
  namukkun-project/src/Pages/MainPage.js
  namukkun-project/src/Recoil/Atom.js
Labels: Feat

#59 Feat: 댓글 클백 연결 완료
  namukkun-project/src/API/AxiosAPI.js
  namukkun-project/src/Components/Postit_Components/DraggablePostit.js
  namukkun-project/src/Components/Postit_Components/Modal.js
  namukkun-project/src/Components/Postit_Components/styledComponents.js
  namukkun-project/src/Pages/Postit.js
Labels: Feat

#60 Feat: 포스트 제목 클릭시 상세페이지로 이동
  namukkun-project/src/App.js
  namukkun-project/src/Components/ListAll_Components/Contents.js
  namukkun-project/src/Components/List_Components/NewPost.js
  namukkun-project/src/Components/List_Components/PopularPost.js
  namukkun-project/src/Components/MainPage_Components/GreatIdeaPage.js
  namukkun-project/src/Components/MainPage_Components/IdeaPage.js
Labels: Feat

#65 Feat: 마이페이지 삭제/수정/ 상세페이지 이동 기능 완료
  namukkun-project/src/API/AxiosAPI.js
  namukkun-project/src/App.js
  namukkun-project/src/Assets/Img/return.svg
  namukkun-project/src/Components/Modify_Components/Modify.js
  namukkun-project/src/Components/Modify_Components/ModifyModal.js
  namukkun-project/src/Components/Mypage_Components/EndAll.js
  namukkun-project/src/Components/Mypage_Components/EndAllPost.js
  namukkun-project/src/Components/Mypage_Components/IngAllPost.js
  namukkun-project/src/Components/Mypage_Components/IngPost.js
  namukkun-project/src/Components/Mypage_Components/TempPost.js
  namukkun-project/src/Pages/ModifyPage.js
Labels: Feat

#68 Feat: 수정 삭제 route랑 클백 연결
  namukkun-project/src/Components/Postit_Components/AdviseDelete.js
  namukkun-project/src/Components/Postit_Components/DeleteModal.js
  namukkun-project/src/Components/Postit_Components/DetailContent.js
  namukkun-project/src/Components/Postit_Components/styledComponents.js
  namukkun-project/src/Pages/Postit.js
Labels: Feat

#70 Feat: 수정페이지 get완료
  namukkun-project/src/API/AxiosAPI.js
  namukkun-project/src/Components/Modify_Components/Modify.js
  namukkun-project/src/Components/Postit_Components/DeleteModal.js
  namukkun-project/src/Components/Postit_Components/DetailContent.js
Labels: Feat

#72 Feat: 내용에 태그 적용
  namukkun-project/src/Components/Postit_Components/DetailContent.js
Labels: Feat

#78 Design: 모달 수정
  namukkun-project/src/Assets/Img/hoversendbrave.svg
  namukkun-project/src/Assets/Img/notfoundimg.svg
  namukkun-project/src/Assets/Img/onclicksendbrave.svg
  namukkun-project/src/Assets/Img/sendbrave.svg
  namukkun-project/src/Components/Mypage_Components/DeleteModal.js
  namukkun-project/src/Components/Postit_Components/DetailContent.js
  namukkun-project/src/Components/Postit_Components/Modal.js
  namukkun-project/src/Components/Postit_Components/styledComponents.js
  namukkun-project/src/Pages/NotFound.js
Labels: Design

#81 Design: 추천 로고 디테일 수정
  namukkun-project/src/API/AxiosAPI.js
  namukkun-project/src/Assets/Img/nexbutton.svg
  namukkun-project/src/Assets/Img/nextbutton.svg
  namukkun-project/src/Components/BeforeLogin_Components/BeforeLogin.js
  namukkun-project/src/Components/ListAll_Components/Contents.js
  namukkun-project/src/Components/ListAll_Components/ShowList.js
  namukkun-project/src/Components/List_Components/NewPost.js
  namukkun-project/src/Components/MainPage_Components/GreatIdeaPage.js
  namukkun-project/src/Components/MainPage_Components/IdeaPage.js
  namukkun-project/src/Components/Modify_Components/ModifyModal.js
  namukkun-project/src/Components/Postit_Components/DraggablePostit.js
  namukkun-project/src/Components/Postit_Components/styledComponents.js
  namukkun-project/src/Components/WritingPage_Components/WritingModal.js
  namukkun-project/src/Pages/Postit.js
Labels: Design

#93 Design: about 페이지 애니메이션 추가
  namukkun-project/src/API/AxiosAPI.js
  namukkun-project/src/Components/About_Components/AboutPage.js
  namukkun-project/src/Components/Layout_Components/FixList.js
  namukkun-project/src/Components/Layout_Components/Spinner.js
  namukkun-project/src/Components/List_Components/NewPost.js
  namukkun-project/src/Components/Login_Components/KaKaoLogin.js
  namukkun-project/src/Components/Modify_Components/Modify.js
  namukkun-project/src/Components/Mypage_Components/EndPost.js
  namukkun-project/src/Components/Mypage_Components/IngPost.js
  namukkun-project/src/Pages/MyPage.js
Labels: Design

#96 Design: 게시물 없을 경우 예외처리
  namukkun-project/src/Assets/Img/HowAbout.svg
  namukkun-project/src/Assets/Img/bottomimg.svg
  namukkun-project/src/Assets/Img/bottomimgbd.svg
  namukkun-project/src/Assets/Img/bottomimgwd.svg
  namukkun-project/src/Assets/Img/nopost.svg
  namukkun-project/src/Components/List_Components/PopularPost.js
  namukkun-project/src/Components/MainPage_Components/GreatIdeaPage.js
  namukkun-project/src/Components/Mypage_Components/EndAll.js
  namukkun-project/src/Components/Mypage_Components/EndAllPost.js
  namukkun-project/src/Components/Mypage_Components/EndPost.js
  namukkun-project/src/Components/Mypage_Components/IngAll.js
  namukkun-project/src/Components/Mypage_Components/IngAllPost.js
  namukkun-project/src/Components/Mypage_Components/IngPost.js
  namukkun-project/src/Components/Postit_Components/styledComponents.js
  namukkun-project/src/Pages/MainPage.js
  namukkun-project/src/Pages/MyPage.js
Labels: Design

#99 Bug: 포스트 좋아요 오류
  .DS_Store
  namukkun-project/src/API/AxiosAPI.js
  namukkun-project/src/App.js
  namukkun-project/src/Components/About_Components/AboutPage.js
  namukkun-project/src/Components/BeforeLogin_Components/BeforeLogin.js
  namukkun-project/src/Components/Layout_Components/FixList.js
  namukkun-project/src/Components/Layout_Components/Header.js
  namukkun-project/src/Components/ListAll_Components/ShowList.js
  namukkun-project/src/Components/List_Components/ListSelectRegion.js
  namukkun-project/src/Components/List_Components/NewPost.js
  namukkun-project/src/Components/List_Components/PopularPost.js
  namukkun-project/src/Components/Login_Components/KaKaoLogin.js
  namukkun-project/src/Components/MainPage_Components/Banner.js
  namukkun-project/src/Components/MainPage_Components/GreatIdeaPage.js
  namukkun-project/src/Components/MainPage_Components/IdeaPage.js
  namukkun-project/src/Components/Modify_Components/Modify.js
  namukkun-project/src/Components/Mypage_Components/EndAll.js
  namukkun-project/src/Components/Mypage_Components/IngAll.js
  namukkun-project/src/Components/Mypage_Components/RegionChangeModal.js
  namukkun-project/src/Components/Mypage_Components/TemModify.js
  namukkun-project/src/Components/Mypage_Components/TempPost.js
  namukkun-project/src/Components/Postit_Components/AdviseDelete.js
  namukkun-project/src/Components/Postit_Components/DetailContent.js
  namukkun-project/src/Components/Postit_Components/DraggablePostit.js
  namukkun-project/src/Components/WritingPage_Components/Writing.js
  namukkun-project/src/Pages/MainPage.js
  namukkun-project/src/Pages/ModifyPage.js
  namukkun-project/src/Pages/MyPage.js
  namukkun-project/src/Pages/Postit.js
  namukkun-project/src/Pages/WritingPage.js
  namukkun-project/src/Recoil/Atom.js
Labels: Bug

#100 Design: 게시물 이미지 처리 밑 글씨체 수정
  README.md
  namukkun-project/src/Components/About_Components/AboutPage.js
  namukkun-project/src/Components/BeforeLogin_Components/BeforeLogin.js
  namukkun-project/src/Components/Layout_Components/Header.js
  namukkun-project/src/Components/ListAll_Components/Contents.js
  namukkun-project/src/Components/ListAll_Components/ShowList.js
  namukkun-project/src/Components/List_Components/NewPost.js
  namukkun-project/src/Components/List_Components/PopularPost.js
  namukkun-project/src/Components/Login_Components/KaKaoLogin.js
  namukkun-project/src/Components/Login_Components/LoginModal.js
  namukkun-project/src/Components/MainPage_Components/Banner.js
  namukkun-project/src/Components/Mypage_Components/EndAll.js
  namukkun-project/src/Components/Mypage_Components/EndPost.js
  namukkun-project/src/Components/Mypage_Components/IngAll.js
  namukkun-project/src/Components/Postit_Components/DetailContent.js
  namukkun-project/src/Components/Postit_Components/styledComponents.js
  namukkun-project/src/Components/SelectRegion_Components/SelectRegions.js
Labels: Design

#103 Feat: 포스티잇 유저 정보 디폴트 값
  namukkun-project/src/Components/BeforeLogin_Components/BeforeLogin.js
  namukkun-project/src/Components/ListAll_Components/ShowList.js
  namukkun-project/src/Components/MainPage_Components/Banner.js
  namukkun-project/src/Components/Postit_Components/DetailContent.js
  namukkun-project/src/Components/Postit_Components/DraggablePostit.js
  namukkun-project/src/Components/SelectRegion_Components/SelectRegions.js
Labels: Feat
